### ISSUE TITLE
[FEAT] StartPage UI 구현

### ISSUE THREAD

**Issue by Shin-jun** [DeveloperAcademy-POSTECH/MC3-Team11-TopicRun#6]
### 문제 상황
- UIKit을 활용한 StartPage 구현

### 해결 방안
- Figma에 맞춰 개발
 
### TODO
- [x]  StartPageView 만들기
- [x]  textfield 값 모두 채워지지 않았을 경우 button disabled

### 비고 및 한계
<img width="165" alt="스크린샷 2022-07-18 15 35 22" src="https://user-images.githubusercontent.com/70710995/179456357-c54242d8-2023-4cd1-bf92-397837b8702b.png">

---
> 진행 상황은 Comment로 아래에 달아주세요
ex) 220405: 00 추가

**Comment by Shin-jun** [comment]
07.19 StartPageView 만들었습니다.
만드는 와중 큰 문제에 직면했습니다. 닉네임 작성시 Keyboard가 올라올 때 뷰를 가리는 부분을 상정하지 않았습니다.
현재 생각한 방법은 두가지로
- keyboard 커스텀을 가져온다.
- 닉네임 작성 화면을 따로 생성한다.

보시고 의견 주세요~!
@KyuHwan00 @ocner1435 @shwoghk14

**Comment by ocner1435** [comment]
커스텀으로 진행해주시면 감사하겠습니다

**Comment by Shin-jun** [comment]
네 감사합니다!

**Comment by Shin-jun** [comment]
07.20
StartPageView 완성했습니다.
